apiVersion: v1
kind: Service
metadata:
  name: vaued-ecom-service
spec:
  type: NodePort
  selector:
    app: vaued-ecom
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080  # You choose this (in range 30000–32767)
