# grafana/provisioning/alerting/alert_rules.yml
apiVersion: 1

groups:
  - name: E-commerce Alerts
    folder: E-commerce
    interval: 60s
    rules:
      - uid: high_response_time
        title: High API Response Time
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              expr: sum(http_request_duration_seconds_sum) / sum(http_request_duration_seconds_count) > 0.5
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              refId: B
              type: reduce
              reducer: last
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          description: "API response time is higher than 500ms for more than 5 minutes"
          summary: "High API response time detected"
        labels:
          severity: warning
          
      - uid: high_error_rate
        title: High API Error Rate
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              expr: sum(http_requests_total{status_code=~"4..|5.."}) / sum(http_requests_total) > 0.05
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              expression: A
              refId: B
              type: reduce
              reducer: last
        noDataState: NoData
        execErrState: Error
        for: 5m
        annotations:
          description: "API error rate is higher than 5% for more than 5 minutes"
          summary: "High API error rate detected"
        labels:
          severity: critical